# Generated by Django 5.0.7 on 2025-12-19 12:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('role_type', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('HR_ADMIN', 'HR Administrator'), ('HR_MANAGER', 'HR Manager'), ('DEPARTMENT_HEAD', 'Department Head'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('PAYROLL_ADMIN', 'Payroll Administrator'), ('RECRUITMENT', 'Recruitment Officer')], default='EMPLOYEE', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_approve_leaves', models.BooleanField(default=False)),
                ('can_manage_payroll', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_recruitment', models.BooleanField(default=False)),
                ('can_manage_attendance', models.BooleanField(default=False)),
                ('can_manage_assets', models.BooleanField(default=False)),
                ('can_manage_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('force_password_change', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('session_token', models.CharField(blank=True, max_length=100, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10)),
                ('receive_email_notifications', models.BooleanField(default=True)),
                ('receive_sms_notifications', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_successful', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/%Y/%m/')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+263771234567' or '0771234567'", regex='^\\+263[0-9]{9}$|^0[0-9]{9}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+263771234567' or '0771234567'", regex='^\\+263[0-9]{9}$|^0[0-9]{9}$')])),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('national_id', models.CharField(blank=True, help_text='Zimbabwe National ID Number (e.g., 63-123456A63)', max_length=20, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_number', models.CharField(blank=True, help_text='ZIMRA Tax Number', max_length=20, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Mutare', 'Mutare'), ('Gweru', 'Gweru'), ('Kwekwe', 'Kwekwe'), ('Kadoma', 'Kadoma'), ('Masvingo', 'Masvingo'), ('Chinhoyi', 'Chinhoyi'), ('Marondera', 'Marondera'), ('Norton', 'Norton'), ('Chegutu', 'Chegutu'), ('Bindura', 'Bindura'), ('Beitbridge', 'Beitbridge'), ('Redcliff', 'Redcliff'), ('Victoria Falls', 'Victoria Falls'), ('Hwange', 'Hwange'), ('Rusape', 'Rusape'), ('Chiredzi', 'Chiredzi'), ('Kariba', 'Kariba'), ('Karoi', 'Karoi')], max_length=100, null=True)),
                ('province', models.CharField(blank=True, choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Manicaland', 'Manicaland'), ('Mashonaland Central', 'Mashonaland Central'), ('Mashonaland East', 'Mashonaland East'), ('Mashonaland West', 'Mashonaland West'), ('Masvingo', 'Masvingo'), ('Matabeleland North', 'Matabeleland North'), ('Matabeleland South', 'Matabeleland South'), ('Midlands', 'Midlands')], max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Zimbabwe', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20, null=True)),
                ('nationality', models.CharField(default='Zimbabwean', max_length=50)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=17, null=True)),
                ('next_of_kin_address', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Harare', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('sn', 'Shona'), ('nd', 'Ndebele')], default='en', max_length=10)),
                ('profile_visible_to_colleagues', models.BooleanField(default=True)),
                ('phone_visible_to_colleagues', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'is_active'], name='accounts_cu_email_d617b5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email_verification_token'], name='accounts_cu_email_v_64eec8_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['session_token'], name='accounts_cu_session_b7bbb5_idx'),
        ),
    ]
