# Generated by Django 5.2.8 on 2025-11-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('days_allowed_per_year', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True)),
                ('min_days_notice', models.IntegerField(default=7)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('can_be_carried_forward', models.BooleanField(default=False)),
                ('max_carryforward_days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gender_specific', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#10B981', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_service_months', models.IntegerField(default=0)),
                ('applies_to_employment_types', models.JSONField(default=list)),
                ('accrual_method', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly Accrual'), ('quarterly', 'Quarterly')], default='yearly', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leaves.leavetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField()),
                ('contact_during_leave', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to='accounts.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_handovers', to='employees.employee')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_rejections', to='accounts.user')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='leaves_leav_employe_7236fb_idx'), models.Index(fields=['start_date', 'end_date'], name='leaves_leav_start_d_96457d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
