# Generated by Django 5.0.7 on 2025-12-22 05:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_maternity_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paternity_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='applies_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Optional holiday'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Holiday occurs every year on the same date'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='rate_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='additional_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='covering_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_leaves', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='handover_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='default_days_allocated',
            field=models.PositiveIntegerField(default=22, help_text='Annual leave days (Zimbabwe: 22 working days per year)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='icon',
            field=models.CharField(default='fa-plane', help_text='Icon class name', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='requires_document',
            field=models.BooleanField(default=False, help_text='Requires supporting documentation'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'year'], name='leaves_leav_employe_194109_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['leave_type', 'year'], name='leaves_leav_leave_t_10c922_idx'),
        ),
    ]
