# Generated by Django 5.0.7 on 2025-12-19 12:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PRODUCTIVITY', 'Productivity'), ('QUALITY', 'Quality'), ('TEAMWORK', 'Teamwork'), ('LEADERSHIP', 'Leadership'), ('COMMUNICATION', 'Communication'), ('INNOVATION', 'Innovation'), ('ATTENDANCE', 'Attendance'), ('TECHNICAL', 'Technical Skills')], max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Weight in overall performance score', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PERSONAL', 'Personal Development'), ('DEPARTMENTAL', 'Departmental'), ('ORGANIZATIONAL', 'Organizational'), ('SKILL_DEVELOPMENT', 'Skill Development'), ('PROJECT', 'Project-based')], default='PERSONAL', max_length=50)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=50)),
                ('required_resources', models.TextField(blank=True)),
                ('support_needed', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_set', to='employees.employee')),
            ],
            options={
                'ordering': ['-due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('review_frequency_days', models.PositiveIntegerField(default=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Successfully Completed'), ('EXTENDED', 'Extended'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('performance_issues', models.TextField()),
                ('expected_improvements', models.TextField()),
                ('success_criteria', models.TextField()),
                ('support_provided', models.TextField()),
                ('resources_allocated', models.TextField(blank=True)),
                ('training_required', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('milestones_achieved', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('final_recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_plans', to='employees.employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pips', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('PROBATION', 'Probation Review'), ('QUARTERLY', 'Quarterly Review'), ('ANNUAL', 'Annual Review'), ('MID_YEAR', 'Mid-Year Review'), ('PROJECT', 'Project Review'), ('ADHOC', 'Ad-hoc Review')], max_length=20)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('SELF_ASSESSMENT', 'Self Assessment'), ('MANAGER_REVIEW', 'Manager Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Overall rating from 1 (Poor) to 5 (Excellent)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_assessment_completed', models.BooleanField(default=False)),
                ('self_assessment_date', models.DateField(blank=True, null=True)),
                ('self_assessment_comments', models.TextField(blank=True)),
                ('self_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('development_plan', models.TextField(blank=True)),
                ('training_recommendations', models.TextField(blank=True)),
                ('career_aspirations', models.TextField(blank=True)),
                ('goals_achieved', models.PositiveIntegerField(default=0)),
                ('goals_total', models.PositiveIntegerField(default=0)),
                ('salary_adjustment_recommended', models.BooleanField(default=False)),
                ('salary_adjustment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('promotion_position', models.CharField(blank=True, max_length=200)),
                ('action_items', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('employee_acknowledged', models.BooleanField(default=False)),
                ('employee_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('employee_signature', models.TextField(blank=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('reviewer_signed', models.BooleanField(default=False)),
                ('reviewer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('supporting_documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
                ('goals_discussed', models.ManyToManyField(blank=True, related_name='reviews', to='performance.goal')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to='employees.employee')),
            ],
            options={
                'ordering': ['-review_date', 'employee'],
            },
        ),
    ]
