# Generated by Django 5.0.7 on 2025-12-20 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation rate percentage', max_digits=5)),
                ('default_useful_life_years', models.PositiveIntegerField(default=5, help_text='Expected useful life in years')),
                ('requires_regular_maintenance', models.BooleanField(default=False)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=90, help_text='Days between maintenance checks')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='assets.assetcategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='asset_qr_codes/')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value after depreciation', max_digits=12, null=True)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated value at end of useful life', max_digits=12)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=100)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('warranty_terms', models.TextField(blank=True)),
                ('warranty_provider', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('IN_REPAIR', 'In Repair'), ('IN_MAINTENANCE', 'In Maintenance'), ('DISPOSED', 'Disposed'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('DAMAGED', 'Damaged Beyond Repair'), ('RETIRED', 'Retired')], default='IN_STOCK', max_length=20)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=20)),
                ('current_location', models.CharField(blank=True, help_text='Physical location of asset', max_length=200)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('is_insured', models.BooleanField(default=False)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_method', models.CharField(blank=True, choices=[('SOLD', 'Sold'), ('DONATED', 'Donated'), ('SCRAPPED', 'Scrapped'), ('TRADED', 'Traded In'), ('RECYCLED', 'Recycled')], max_length=50)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disposal_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asset_photos/')),
                ('is_critical', models.BooleanField(default=False, help_text='Critical asset requiring special attention')),
                ('is_portable', models.BooleanField(default=False)),
                ('requires_checkout', models.BooleanField(default=True, help_text='Requires formal checkout process')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('current_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='employees.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_assets', to='employees.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('opening_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('UNITS_OF_PRODUCTION', 'Units of Production')], default='STRAIGHT_LINE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('ROUTINE', 'Routine Maintenance'), ('REPAIR', 'Repair'), ('UPGRADE', 'Upgrade'), ('INSPECTION', 'Inspection'), ('CLEANING', 'Cleaning'), ('CALIBRATION', 'Calibration')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('work_performed', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('service_provider', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('parts_replaced', models.TextField(blank=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('DAMAGED', 'Returned Damaged'), ('LOST', 'Lost'), ('STOLEN', 'Stolen')], default='ACTIVE', max_length=20)),
                ('condition_out', models.TextField(blank=True, help_text='Condition of asset upon assignment')),
                ('condition_in', models.TextField(blank=True, help_text='Condition of asset upon return', null=True)),
                ('responsibility_agreement', models.BooleanField(default=False, help_text='Employee accepted responsibility')),
                ('agreement_signed_at', models.DateTimeField(blank=True, null=True)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=0, help_text='Charge for damages', max_digits=10)),
                ('damage_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_history', to='employees.employee')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['asset', 'status'], name='assets_asse_asset_i_ff1ed0_idx'), models.Index(fields=['employee', 'assigned_date'], name='assets_asse_employe_cb51f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_tag', 'status'], name='assets_asse_asset_t_fc3384_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_asse_serial__401a52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciation',
            unique_together={('asset', 'year', 'month')},
        ),
    ]
